spring:
  application:
    name: transaction-service
  profiles:
    active: docker

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  datasource:
    url: ${DATABASE_URL:}
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  liquibase:
    change-log: db/migration/db-changelog.yaml
    default-schema: transactions
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    parameters:
      textColumnType: TEXT
  sql:
    init:
      mode: always
      continue-on-error: false
  cloud:
    config:
      enabled: false

logging:
  level:
    "liquibase" : info

management:
  endpoint:
    health:
      enabled: true

