spring:
  application:
    name: transaction-service
  profiles:
    active: docker

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://192.168.1.116:3306/transactions
    driverClassName: com.mysql.cj.jdbc.Driver
    username: service
    password: !23qweASD

  liquibase:
    change-log: db/migration/db-changelog.yaml
    default-schema: transactions
  sql:
    init:
      mode: always
      continue-on-error: false

logging:
  level:
    "liquibase" : info

management:
  endpoint:
    health:
      enabled: true

